application: youtify
version: 13
runtime: python
api_version: 1

builtins:
- remote_api: on

error_handlers:
  - file: html/error.html

  - error_code: over_quota
    file: html/quota.html

handlers:

- url: /admin/import_old_translations
  script: import_old_translations.py
  login: admin

- url: /admin/migrations/.*
  script: migrations.py
  login: admin

- url: /admin/minimizer
  script: minimizer.py
  login: admin

- url: /admin/fakesetup
  script: fakesetup.py
  login: admin

- url: /admin/filter
  static_files: html/filter.html
  upload: html/filter.html
  login: admin

- url: /admin
  script: admin.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: /me/.*
  script: me.py

- url: /api/users.*
  script: users.py

- url: /about
  static_files: html/popups/about.html
  upload: html/popups/about.html
  #expiration: "1d"

- url: /yourbrowsersucks
  script: sucks.py

- url: /yourdecisionrocks
  script: sucks.py

- url: /cron/generate_youtube_toplist.*
  script: youtube_toplist.py
  login: admin

- url: /cron/generate_flattr_toplist.*
  script: flattr_toplist.py
  login: admin

- url: /flattr_submit.*
  script: flattr_submit.py

- url: /api/playlists.*
  script: playlists.py

- url: /api/search.*
  script: search.py

- url: /api/favorites.*
  script: favorites.py

- url: /cron/store_pings
  script: ping.py
  login: admin

- url: /pinggraph
  script: ping.py
  login: admin

- url: /ping.*
  script: ping.py

- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /images
  static_dir: images
  expiration: "1d"

- url: /translations
  script: translations.py
  login: required

- url: /translations/.*
  script: translations.py
  login: required

- url: /phrases
  script: phrases.py

- url: /phrases/.*
  script: phrases.py

- url: /languages
  script: languages.py

- url: /languages/.*
  script: languages.py

- url: /snapshots
  script: snapshots.py

- url: /snapshots/.*
  script: snapshots.py

- url: /api/translations/.*
  script: snapshots.py
  
- url: /robots.*
  static_files: robots.txt
  upload: robots.txt
  expiration: "1d"

- url: /flattr.*
  script: flattr.py
  login: required

- url: /.*
  script: main.py

